### ISSUE TITLE
contrast

### ISSUE THREAD

**Issue by freekatet** [keijiro/KlakSyphon#1]
Hi!
I have been using your asset successfuly on osx 10.13.2 unity 2018.1.0b11
tho i noticed that the stream was way much more contrasted on the syphon client side than the original stream. Is it something you experience too on your side ?

thanks!
<img width="697" alt="screen shot 2018-04-26 at 8 26 07 pm" src="https://user-images.githubusercontent.com/2891340/39343123-193510ce-4990-11e8-90b8-098f8f68989b.png">

**Comment by keijiro** [comment]
At the moment, it gives wrong luminance because I haven't implemented proper color space conversion. Please note that this plugin is still under an experimental phase and not ready for practical use. I'll look into it after fixing more important stuff.

**Comment by keijiro** [comment]
Fixed in the recent version.
