### ISSUE TITLE
'SyphonClient._targetMaterialProperty' is never assigned to ERROR  2018.3.0f2 <Metal>

### ISSUE THREAD

**Issue by makaruk** [keijiro/KlakSyphon#11]
Dear Keijiro,

Thank You for Your continous support of KlaK Syphon.

I wonder if You could help me with this situation:

I'm running a fresh Scene in Unity 2018.3.0f2 <Metal>, on OSX 10.14. I previously had no problems with running Klak Syphon.

When I place the SYphon Server on My Main Camera I get the following error:

`Assets/Klak/Syphon/Runtime/SyphonClient.cs(75,34): warning CS0649: Field 'SyphonClient._nullTexture' is never assigned to, and will always have its default value null`

The camera screen output of Klak Syphon is blank - however the Syphon input is detected in third party software working as Syphon Clients.

The same problem persists after I build the application.

Please find the LOG file attached

Any Help would be very appreciated.

Kind Regards

[Editor.log](https://github.com/keijiro/KlakSyphon/files/2677903/Editor.log)

**Comment by keijiro** [comment]
```
Assets/Klak/Syphon/Runtime/SyphonClient.cs(75,34): warning CS0649:
Field 'SyphonClient._nullTexture' is never assigned to,
and will always have its default value null
```

This is just a warning message emit by the new C# compiler. It doesn't cause anything -- you can simply ignore it. Or you can downgrade the scripting runtime version to .NET 3.5 Equivalent from Player Settings.

I tested it on Unity 2018.3.0f2 but couldn't reproduce.

- Could you check if it can reproduce with a minimal project?
- What happens if you downgrade the scripting runtime version to .NET 3.5?

**Comment by makaruk** [comment]
Dear Keijiro,

Thank You for Your support.

The problem was in fact the Scripting Runtime Version setting in Unity Project Settings - when I changed the Scripting Runtime Version from **.NET 4.x Equivalent** to **.NET 3.5 Equivalent (Deprecated)** the Klak Syphon Server started working again as normal. 

This was the solution to the problem - Thank You very much!!!!
