### ISSUE TITLE
Red screen problem with RenderTextureFormat.ARGB32

### ISSUE THREAD

**Issue by shiyamon** [keijiro/KlakSyphon#13]
Hi, I got the similar problem with other issue. #12 

When I send a RenderTexture in the format of RenderTextureFormat.ARGB32, RenderTextureFormat.ARGBHalf or RenderTextureFormat.ARGBFloat, the receiver shows red texture.
RenderTextureFormat.Default is working here.

**Comment by shiyamon** [comment]
I did further try and it turns out that enabling enableRandomWrite also causes red texture problem.

**Comment by Tongzhou-Yu** [comment]
I have the same problem with Syphon as mentioned by MTB-Yoshida :(

**Comment by keijiro** [comment]
I think it doesn't reproduce with 1.0.0. Please reopen this issue if it still reproduces.
