### ISSUE TITLE
Does not work in RT Mode (Unity 2019.3.2f1)

### ISSUE THREAD

**Issue by cruxxxxxx** [keijiro/KlakSyphon#14]
Works in Camera Capture mode, but when switching to RT mode, Syphon Server sends empty image. RT looks good on Unity side. 

Running Unity 2019.3.2f1 on Mac OSX 10.14.5. Player is set to Metal.

**Comment by gmarinosyan** [comment]
Having the same issue with Unity 2020.1.0f1 on MacOS 10.15.5. Empty image is sent when using render texture mode, although the size of the sent image is correct.

**Comment by keijiro** [comment]
I think this issue doesn't reproduce with 1.0.0. Please reopen it if it still reproduces.
