### ISSUE TITLE
Fuzzy or blurry TextMeshPro content. 

### ISSUE THREAD

**Issue by olgv** [keijiro/KlakSyphon#15]
I notice al UI TextMeshPro elements are broadcasted blurry. 
Changing the texture size when creating a new SDF font seems to affect how Syphon sees it, but no matter what size I try none looks sharp.

Any suggestions appreciated.
Thank you

**Comment by keijiro** [comment]
Could you provide a screenshot and a minimal project that reproduces the issue?

**Comment by olgv** [comment]
Funny enough I was trying to replicate it in a clean `2019.4` project and it comes out sharp and as it should be. I will try to isolate parts of the project so I can share this with you.

The setup used was `TMP - Text` (Mesh) and the Canvas as `World Space` ... that was the only way I managed to make the text visible to the Syphon Server. 
And I tried generating the TMP tables at different resolutions, but the higher I was getting the worse it rendered, which made no sense.

Later on I realised that having the Canvas as `Screen Space - Camera` renders the `TMP - Text (UI)`.

I am attaching 2 images to see how it looks in the builds (compiled with `2019.3.13`)
![Screenshot 2020-06-09 at 23 49 24](https://user-images.githubusercontent.com/5272004/84451000-4e04a380-ac41-11ea-9a20-77f09d8b6f33.png)
![Screenshot 2020-05-25 at 00 32 12](https://user-images.githubusercontent.com/5272004/84451005-5066fd80-ac41-11ea-9180-5c2186f874f6.png)

I will get back with a project. Thank you.

**Comment by olgv** [comment]
I found the bug. It relates to the FXAA in the Post Processing Layer.
If I turn it off everything is fine.

![Screenshot 2020-06-12 at 20 04 38](https://user-images.githubusercontent.com/5272004/84542700-8790e980-ace9-11ea-9a2b-5eefbe05b6e0.png)


This persists even without the Syphon Server class attached. 
Therefore **not a Syphon bug but a Unity PP & TMP**.
