### ISSUE TITLE
Get Server Names

### ISSUE THREAD

**Issue by sachismo** [keijiro/KlakSyphon#16]
I am wondering if there is any implementation in this plugin to get the names of all available servers. I am able to select specific servers by name, but I am wanting to make a GUI that is populated by all available servers. If this is already available I'm not sure how to use it. Is there any tool that can work similar to SpoutManager.GetSourceNames() from your Unity Spout plugin?

Thanks for all your great work on these!

**Comment by keijiro** [comment]
No, there is no such function.
