### ISSUE TITLE
 It doesn't work. I want to help.

### ISSUE THREAD

**Issue by um38s** [keijiro/KlakSyphon#18]
I ran it according to the contents you uploaded
I got the following error message.
I can't find a solution, so I'm posting content to get help.

DllNotFoundException: KlakSyphon
Klak.Syphon.SyphonServer.Update () (at Assets/Klak/Syphon/Runtime/SyphonServer.cs:99)

**Comment by keijiro** [comment]
How about running the sample project contained in this repository?

**Comment by um38s** [comment]
I tried the sample test, but the following error came out.

![캡처_2021_02_27_23_05_57_896](https://user-images.githubusercontent.com/15072212/109389717-e1594280-7950-11eb-83b6-846b9ab24e06.png)

**Comment by keijiro** [comment]
Windows?

Syphon is an inter-process frame sharing system for **macOS**.

**Comment by um38s** [comment]
The os I am using is window. 
 If so, I wonder if you can't use syphon on Windows.

나의 iPhone에서 보냄

> 2021. 2. 27. 오후 11:23, Keijiro Takahashi <notifications@github.com> 작성:
> 
> Windows?
> 
> Syphon is an inter-process frame sharing system for macOS.

**Comment by keijiro** [comment]
You can't use Syphon on Windows.

There are some similar systems for Windows, like [Spout](https://spout.zeal.co/).

**Comment by keijiro** [comment]
I'm closing this issue as "not relevant". Please feel free to reopen it for further problems.

**Comment by um38s** [comment]
Yes, I understand.  Thank you so much for the explanation.

나의 iPhone에서 보냄

**Comment by Gamgie** [comment]
Hello,

I want syphon and spout on a crossplatform project (both Mac & Windows).
How can I avoid this message on windows ?
is there a way to no not compile from windows in the editor ? 

Thanks for your help !
