### ISSUE TITLE
Does this work with URP?

### ISSUE THREAD

**Issue by Gabana** [keijiro/KlakSyphon#19]
Hi,

I tried this plugin in my MacBook Pro (Retina, Mid 2012 - OS Catalina 10.15.5) with Unity 2020.3.4 and it works fine. However, it stopped working when using Universal RP. As soon as i set up a profile in PlayerSetting > Graphics it stopped working.

@keijiro Do you know if it would work with other Render Pipelines apart from the standard (built-in) one? Any ideas why it wouldn't work with URP?

Thanks in advance!
D

**Comment by keijiro** [comment]
The camera capture mode only supports the legacy (built-in) render pipeline. You have to use the render texture mode when using SRP.

(Add the SyphonServer component to a non-camera game object and feed renders using a RenderTexture)

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it if the problem still reproduces.

**Comment by Gabana** [comment]
Hi,

Thanks for the quick reply! I tried both modes with RenderTexture and Camera Capture but none of them worked with URP in Mac. It does work in Windows though...

Any idea about why this would happen or how to fix it?

Thanks!

D

**Comment by Gabana** [comment]
I found this other library thatworks with URP in Mac. Actually, if you use the VideoOutput (SRP) with your SyphonServer script, it would work fine

https://github.com/anome/Unity-VideoOutput

**Comment by Gabana** [comment]
Hi @keijiro ,

I am trying to re-open the issue but i cannot since the Owner closed it.

I tried the approach you said: add the SyphonServer component to a non-camera game object and feed renders using a RenderTexture. However, that is not working. I can see that Syphon gets frames and the resolution right, but nothing is displayed, it´s just black. Is there anything else i should try? I am using 2020.3.4 and URP

Thanks in advance!
D

**Comment by MissCalculated** [comment]
I'm also having trouble getting the render texture to work. I use a Macbook Pro M1 on Monterey. I tried it using 2021.3.2f1 intel and 2021.3.4f1 silicon.

The object with the render texture attached shows the camera output correctly in the editor and while playing. That object shows up as an available camera in my Syphon client while playing, however it only shows a black screen in the client.

This happens on both URP, my target platform for this project, and built-in, which I tried just to check it.

In built-in, a camera with the Syphon Server attached does get seen by my Syphon client.

Any thoughts on what I can do to make render textures work in my Syphon client?

Thanks!

**Comment by keijiro** [comment]
Regarding M1 Mac, there is another issue #23 on Unity's side. That's why I can't actively work on it.

**Comment by MissCalculated** [comment]
Thanks for your response :) I just read the material at your link.

I am happy to use the Intel/Rosetta version of Unity for now. Do you think there's a way I can get the render texture method to work if I stick with Rosetta?

**Comment by MissCalculated** [comment]
@keijiro btw this fixed it for me:

https://github.com/noir-neo/KlakSyphon/commit/16aca762f2c05ff62cb809e4f9e2b88d2f740707

**Comment by keijiro** [comment]
I added URP/HDRP support in 1.0.0.
