### ISSUE TITLE
syphonclient crashes unity 2018.1.0b11

### ISSUE THREAD

**Issue by freekatet** [keijiro/KlakSyphon#2]
Hi,
the Syphon client script coming with the release is crashing unity on osx 10.13.2.
I tried on fresh project, same behavior.

I am using a master version prior to the release with no crashes

**Comment by keijiro** [comment]
Please check if you're actually using the latest version (v0.0.2). The previous version (v0.0.1) has the problem about client, and I fixed it in v0.0.2.

**Comment by freekatet** [comment]
This is version 0.0.2
importing a syphon client in a fresh project doesn't crash.
using the new version in a project crash, after taking off every syphon scripts and reinserting them no crash anymore.

I also realized that the old server master version (April 27th) with resolution typed manually in the script were more efficient than the release version. 50 fps vs 30/25fps for the same project at the same resolution.

**Comment by keijiro** [comment]
> I also realized that the old server master version (April 27th) with resolution typed manually in the script were more efficient than the release version. 50 fps vs 30/25fps for the same project at the same resolution.

This is not a problem about Syphon but the rendering resolution. You can improve the performance by decreasing the resolution of the game view by manually setting the resolution from the dropdown menu in the top-left of the game view, or you can use the render texture mode to implicitly set the resolution (this is the most performant way to use the plugin; see the example project for details).

**Comment by keijiro** [comment]
> This is version 0.0.2
> importing a syphon client in a fresh project doesn't crash.
> using the new version in a project crash, after taking off every syphon scripts and reinserting them no crash anymore.

Does it means that the problem has gone and you don't have the problem anymore? I wonder if there is a problem only when updating from the previous implementation.

**Comment by keijiro** [comment]
I'm closing this ticket. Please feel free to reopen for further questions.
