### ISSUE TITLE
Test Project?

### ISSUE THREAD

**Issue by anyusernameleft** [keijiro/KlakSyphon#20]
I'm possibly being dumb but I cannot find the Test Project, without which I have no idea where to start with this excellent looking plugin.
I imported the latest Unity Assets bundle but the Test project didn't come with it and I can't find it to download elsewhere.

**Comment by keijiro** [comment]
This repository contains a test project, so you can clone (or download) the repository and use it as a test project.

> the latest Unity Assets bundle

This project is not relevant to Asset Bundle. I'm afraid that you're reading something incorrect.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by anyusernameleft** [comment]
I cannot find the test project.
Thank you

**Comment by keijiro** [comment]
This repository itself is the test project directory. You can open it with Unity Editor.

**Comment by anyusernameleft** [comment]
I can’t find the test project
I have opened the unity package but there is no test scene

**Comment by anyusernameleft** [comment]
Nor are there any Assets that would indicate a test scene
From your readme with the small images there would appear to be such things but I cannot find them

**Comment by anyusernameleft** [comment]
I cannot find any explanation as to how this is supposed to work.
Thank you

**Comment by anyusernameleft** [comment]
I spent hours looking.
There is no test scene in the Unity package to explain how it works.
Despite the graphics on your ReadMe page

**Comment by anyusernameleft** [comment]
Please explain where the instructions are as to how the plugin works 
Thank you very much for all your work

**Comment by keijiro** [comment]
Do not use the Unity package file. Clone or download the repository.

**Comment by anyusernameleft** [comment]
I am sorry, I do not understand what you mean.
Thank you

**Comment by keijiro** [comment]
Use Google "how to download github repository zip"
