### ISSUE TITLE
Version for Apple silicon (M1) and latest macOS?

### ISSUE THREAD

**Issue by SteveElbows** [keijiro/KlakSyphon#21]
Any chance of an updated version?

MacOS Monterey wants to throw the current versions plugin bundle in the bin. I've tried building it myself in xcode, building an apple silicon version so I can use it with silicon version of Unity editor, but I havent succeeded in making a version that works rather than giving me missing dll errors in recent Unity versions.

Thanks.

**Comment by rsodre** [comment]
At least, you need to build the Syphon framework for arm64 and replace it.
The Syphon notifications have changed recently, maybe Klak need to be updated too.
Not sure if there's anything else to do...
https://github.com/Syphon/Syphon-Framework/

**Comment by keijiro** [comment]
Just out of curiosity, do you still use Syphon often? If so, which app do you use the most?

Personally, I use Windows in most projects these days, so I'm not sure how Syphon is important. I wonder whether if I should invest more time on this project.

**Comment by rsodre** [comment]
Mac VJS still use Syphon for everything when working locally.
The exception is NDI, but only when there's a need to send frames to another machine.

**Comment by keijiro** [comment]
@rsodre Thanks for the valuable input. Could I ask some more questions?

- Do you use the latest version of macOS (Monterey)?
- Do you use M1 Mac for VJing?
- Do you know any VJing app that supports M1 natively?

**Comment by SteveElbows** [comment]
I know what you mean, but the GPU in the M1 Max 32 core Macbook Pro is really quite good, and I really like the quiet fans too. So I'm really enjoying the mac for realtime graphics again.

I'm using Resolume Avenue (and Wire which is a fun node-based system from Resolume). I've got a 3D fluid Sim (Jos Stam Navier-Stokes type of grid-based sim) in Unity and I'm using Resolume output as 2D textures in Unity to create a 3D texture (using a technique similar to zbrush 'shadowbox' way of building 3D from 2D masks) which I then use as the emitter for the fluid sim. For my initial test of this I've used NDI but there is some lag and as I can run both these things on the same computer and still get enough GPU performance, I would much rather use Syphon.

**Comment by SteveElbows** [comment]
Resolume isnt M1 native yet but they are planning proper M1 support in future. Even using Rosetta, performance is really rather good.

Here are someone elses performance test results using same macbook pro that I got: https://resolume.com/forum/viewtopic.php?p=85132#p85132

**Comment by keijiro** [comment]
@SteveElbows Thanks for the feedback. I have used M1 MBA for a year as a development platform, and recently I ordered M1 Max MBP. So, maybe we're in the same situation. Now I'm building a return-to-mac plan, and I wonder how Syphon works with it.

**Comment by SteveElbows** [comment]
Its hard for me to say how well Syphon works with it yet, because I didnt get your Syphon plugin working with Unity on this machine, so I need to find another Syphon app to use instead in the meantime to give me better clues about that! 

Enjoy your M1 Max when you get it, as a laptop experience its quite great! The variable refresh rate support for the screen is a nice bonus. When they make even more 'pro' machines in future with even more GPU cores than these new Max machines have, then I think the mac realtime graphics future will be even brighter!

I forgot to say in previous post that I am rendering my 3D fluid sim using HDRP 12 Local Volumetric Fog, using Unity 2021.2.

**Comment by rsodre** [comment]
> Do you use the latest version of macOS (Monterey)?

As a developer, my strategy has always been to be one release behind, still fully updated. I just upgraded to Big Sur 11.6 so I can install XCode 13 and build for Monterey.

> Do you use M1 Mac for VJing?

Not yet, but I plan to buy one next year

> Do you know any VJing app that supports M1 natively?

MadMapper 5 (just released), Blendy Dome VJ (developed by myself)

**Comment by SteveElbows** [comment]
Here are some early 'programmer art' tests of my setup using NDI instead of Syphon. I didnt have any great Resolume content ready for these tests so the input textures arent animated. And the ones with low framerate are because often I was a bit too greedy by using high volumetric fog settings and fluid sim grid resolution of 256x256x256. I can get 120fps if I use sim res of 128x128x128 and lower the volumetric fog quality settings a bit.

http://pixelromp.com/NDIToFluid.mp4
http://pixelromp.com/NDIToFluidDense.mp4
http://pixelromp.com/NDIToFluidTiled.mp4

**Comment by hayeheerten** [comment]
Hey there,
MadMapper 5 is Apple Silicon native and it's a blast as far as I can tell right now. It'd be really nice to have Syphon functionality in Unity on Apple Silicon to use the two in conjunction. I tried NDI, but I think it's not well suited for local texture sharing.
I've got a M1 Max 14" sitting on my lap and I'll definitely VJ with it.

**Comment by keijiro** [comment]
@hayeheerten That's good to know. I'll try it for testing.

**Comment by Makimono** [comment]
+1, we also use Syphon on a regular basis and would very much appreciate an updated version of the plugin for Apple Silicon! Our team uses Syphon with Touchdesigner, Mad Mapper, Resolume, Isadora and our own app Tagtool, among others.

**Comment by sachismo** [comment]
+1 on this tool!! Syphon is alive and well once again for live visuals

Would be willing to pay a bounty for this + the ability to get the list of available servers on Unity :)

**Comment by vadimkrutovlv** [comment]
+1 I would also like to have this plugin working with Apple Silicon chips and Monterey.

**Comment by keijiro** [comment]
Apple silicon support was added in 0.0.4.
