### ISSUE TITLE
Step by step instructions

### ISSUE THREAD

**Issue by a25df** [keijiro/KlakSyphon#22]
HI,
I can't get this to work and would need some help.
I would like to send syphon from Resolume and map it's output onto a 3d object in unity.

Steps so far:
- open Resolume Avenue and select texture sharing (syphon) as an output
- open Unity 2021.2.5f1
- create a new 3d scene
- Assets > Import Package > Custom Package : Select and import all from KlakSyphon.unitypackage
- Window > Klak > Syphon Server List : 1 server(s) found. Avenue / Composition
- Then what?

Thanks!

**Comment by keijiro** [comment]
Did you check the sample project?

**Comment by a25df** [comment]
Hi, thank you for your quick reply!

Yes, if you mean by sample project the "Test.unity" in Assets folder?

It opens couple cameras, particle system, cube and plane. Cube and plane are pink and many objects are missing source textures or target texture.

Test Card Camera's Inspector says "The associated script can not be loaded. etc"

Yesterday I opened the Unity for the fist time, so I'm kind a lost here. Any help appreciated!

**Comment by keijiro** [comment]
I haven't used this project for 3 years, so there might be a compatibility issue. Try Unity 2018.1.

**Comment by a25df** [comment]
Hi, I understand.

I'll give 2018.1. a try,

Thank you!

**Comment by a25df** [comment]
I tried with the first build of 2018 but I can't make it to work. 

When Unity is opening the test project, macOs gives this error popup:
“KlakSyphon.bundle” is damaged and can’t be opened. You should move it to the Bin.

Otherwise all in the project looks like the same as before.

**Comment by keijiro** [comment]
Did you try cloning the repository with git? I don't recommend using the .zip download link.

**Comment by a25df** [comment]
Hi,
I cloned the repository with git through terminal. 

I'm not able to get anything new to show up. Client cube is white.
In the Resolume I'm able to get unity servers' output to show, but should it be possible to get Resolume output to show up in the 3d texture in Unity? That's what I'm looking for.

Console gives this error:
Metal: Fragment shader missing texture binding at index 0 (_MainTex / Unlit/Texture)
Metal: Fragment shader missing texture binding at index 0 (_MainTex / Hidden/SceneViewSelected)

When opening the project for the first time, it gave some error about the mismatch of my unity (2018.1.0f2) and the projects creation version (2018.1.0f1). 2018.1.0f2 is the first version available from 2018.

Am I missing something?

Thanks!

**Comment by keijiro** [comment]
Did you select a correct server in the SyphonClient component?

**Comment by a25df** [comment]
Hi,
I was just about to ask what is server, correct, and SyphonClient component when I got it working.

So for objects called Client Cube and Client RT there was "VDMX5" by default in both objects' App Name slot (Inspector>Syphon Client (Script)>App Name). So when you clear that parameter or put, in my case, "Avenue" it shows the output from Resolume. Under App Name slot, there's Server Name which based on my tests needs to be empty. Or you can correct me with that.

With this knowledge I tested with most recent Unity version (2021.2.5f1) and it works. Awesome!!!

This is so cool, thanks!

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by a25df** [comment]
Well, if I make a new object or import a one, what should I do to get the texture showing up?

I copy pasted the Syphon Client (Script) from one object to the new but texture doesn't show up. Inspectors look like identical.

**Comment by keijiro** [comment]
Could you try editing the properties manually (not by copy-paste)? I wonder if it's an issue with the Inspector code.

**Comment by a25df** [comment]
Ok, so it was as easy as just list all materials and drag and drop the correct material on to the object. I don't know how to start from an empty scene, though.

**Comment by keijiro** [comment]
I can't speak English, so it's hard to understand the last reply correctly. My understanding is that you don't know how to use Unity, and it's not relevant to this project.

**Comment by a25df** [comment]
I just try to figure out the logic behind the material. But you are right, tutorials will help me with that.

Thanks.
