### ISSUE TITLE
Syphon Client freezes on M1 Mac

### ISSUE THREAD

**Issue by sachismo** [keijiro/KlakSyphon#23]
Hello and thanks as always for the latest update and your prolific work!! The server list functionality and silicon servers are working flawlessly for me!

I do still have an issue when connecting a client to a server from **Resolume Arena**  This is a very popular application in the live visuals world, but still currently runs under Rosetta.  If i build a client for silicon target it will crash when connected to Resolume (sometimes immediately, sometimes after a few minutes) If I switch build to Intel everything works as expected

This can be re-created by just adding a SyphonClient and overriding an object texture (no external scripts)

software for testing this can be acquired here [https://resolume.com/download/](url) (smaller "no footage" download is at the bottom left of the page)

let me know if I can help any further to recreate or debug this ssue

Thanks Again!

**Comment by keijiro** [comment]
It seem that the client component freezes at `GetNativeTexturePtr` for an unknown reason. It means that the issue may be on Unity's side.

I'll try reproduce the issue and submit a bug report about it.

**Comment by sachismo** [comment]
Gotcha. Thanks for looking into it! 

The intel (rosetta) build is still working flawlessly with very low overhead on an M1 Pro Macbook with the latest OS 12.2 :)

**Comment by keijiro** [comment]
It turned out to be more general issue with the Unity Metal implementation. It even reproduces without Syphon.

I filed a bug report about it. I'd like to wait for a response from QA/R&D.

Unfortunately, there is no instant solution/workaround about this issue. I'd recommend using Rosetta until I get a solution.

**Comment by ylevtov** [comment]
Hi @keijiro - do you have a link to the bug report you submitted directly with Unity so we can track the progress? Thanks!

**Comment by keijiro** [comment]
@ylevtov Here it is: https://issuetracker.unity3d.com/issues/m1-editor-slash-player-freezes-when-calling-getnativetextureptr

**Comment by keijiro** [comment]
According to the issue tracker, the issue was fixed -- Actually, it disappeared by other changes, so they won't fix it (they don't need to fix it).

I close this issue as resolved. Please reopen it if it reproduces on the latest versions of Unity.

**Comment by pholz** [comment]
Not sure if it's exactly the same bug, but on M2, Unity 2023.1b the Syphon plugin does not work: Unity syphon server does not send anything, unity syphon client freezes Unity instantly.
Using Syphon in TouchDesigner on the other side.
