### ISSUE TITLE
Syphon outputs empty frames

### ISSUE THREAD

**Issue by L4Z3RC47** [keijiro/KlakSyphon#25]
OS: MacOS 12.6.1
Unity Version: 2021.3.16f
Klak Syphon version: 0.0.4
Project settings: HDRP, Metal renderer

Issue: When attempting to use Klak Syphon clients only receive blank ("black") frames.

Steps to reproduce:
1: Create a new project with Unity 2021.3.16 from the HDRP core examples.
2: Add Keijiro to the scoped registry and add Klak Syphon from the package manager.
3: Assign the "Syphon Server" script to the main camera
4: Open a Syphon client app (such as Simple Client) and connect to the Unity syphon stream

Expected Result: Client viewer should display frames matching the Unity camera view

Actual Result: Client viewer displays only black frames

<img width="2055" alt="Screen Shot 2022-12-16 at 11 58 48 AM" src="https://user-images.githubusercontent.com/7190465/208215547-79d3e3a4-4f17-4568-bb40-320a0e48aea9.png">

**Comment by keijiro** [comment]
Have you used KlakSyphon successfully? Or this is the first attempt at using it?

**Comment by L4Z3RC47** [comment]
I've used KlakSyphon before however it's been a while. This is the first time trying it on this build.

**Comment by keijiro** [comment]
How about trying the render texture mode?

**Comment by L4Z3RC47** [comment]
Tried that too, same result

**Comment by L4Z3RC47** [comment]
On further testing it seems this is a duplicate of issue #19 
A workaround was posted and shared by https://github.com/noir-neo/KlakSyphon/commit/16aca762f2c05ff62cb809e4f9e2b88d2f740707

**Comment by L4Z3RC47** [comment]
The issue seems to be that SRP does not support OnRenderImage. https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnRenderImage.html
The workaround from @noir-neo gets around this issue by triggering the blitt from the render texture in its own function. It may be desirable to refactor this to make use of the [ScriptableRenderPass](https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@latest/index.html?subfolder=/api/UnityEngine.Rendering.Universal.ScriptableRenderPass.html) and [FullScreen Custom Pass](https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@15.0/manual/Custom-Pass.html) for URP and HDRP respectively

**Comment by marvpaul** [comment]
@keijiro I also had the problem with the black frame which was received by the Syphon client using your latest version of the plugin. I just applied the fix https://github.com/noir-neo/KlakSyphon/commit/16aca762f2c05ff62cb809e4f9e2b88d2f740707  . I think it would really help if you could merge it into your plugin to make it work properly on all devices. 
I'm using it on Macbook Air M1, Unity 2021.3.10f1

**Comment by bikram-cda** [comment]
Should we use intel Unity? I am still facing black screen issue after applying noir-neo fix.

**Comment by keijiro** [comment]
I think this issue doesn't reproduce with 1.0.0. Please reopen it if it still reproduces.
