### ISSUE TITLE
Not connecting to server

### ISSUE THREAD

**Issue by zzzantzzz** [keijiro/KlakSyphon#26]
I've used your Unity Spout plugin with AfterEffects as server sending to Unity on Windows 10 which works so well!
I've now been asked to do the same thing on MacOS so I'm using this KlakSyphon in Unity instead, but Unity is not connecting to the server (AfterEffects).

MacOS 12.1 M1 chip
Unity 2021.3.3f1
AfterEffects 2021
Im using this AE plugin: https://tobiasebsen.gumroad.com/l/aesyphon

I've tried running AE with and without Rosetta but Unity Script still can't connect to server.

I can give you a copy of the AE plugin if that would help?

Any ideas why Unity script can't connect?
Any suggestions on what I could try next?

**Comment by keijiro** [comment]
How about Simple Syphon Server/Client?

**Comment by keijiro** [comment]
I close this issue for inactivity. Please reopen it if it still reproduces.
