### ISSUE TITLE
[Question] How to get it to work with OpenGL core?

### ISSUE THREAD

**Issue by lukasIO** [keijiro/KlakSyphon#3]
Hi,

I realise this is a bit of a weird question, but the problem I'm having is that Unity seems to only work with a single display on Metal API as of now. With the OpenGL API I can use multiple displays... 
Do you have any idea for a workaround to get syphon and multiple displays at the same time? Or could you share some insight in how to make syphon work for OpenGL ?

Thanks!

**Comment by keijiro** [comment]
- If Unity on Metal has an issue with multiple displays, it should be fixed. Have you already reported it?
- I'm not very motivated to reimplement the plugin for OpenGL because Apple announced they're going to deprecate it in the coming version of macOS.

**Comment by lukasIO** [comment]
Yes. I reported it, but didn't hear back from the Unity Team.

The lack of motiviation to reimplement it for a deprecated Graphics API is completely understandable, I was naively hoping it could be wrapped or ported to OpenGL in a rather easy way...

**Comment by nicoloserafino** [comment]
@lukasIO try Mad mapper: two Unity cameras streamed trough KlakSyphon, then Mad mapper with to projectors/display/etc

**Comment by olgv** [comment]
@lukasIO you can use Keijiro's [Funnel](https://github.com/keijiro/Funnel) for OpenGL support. Though discontinued (the app window can be glitchy in certain situations but the Syphon output comes clean) is still the only way for now if using it on old MACs that don't support Metal (eg: Mid 2011 hardware).

**Comment by keijiro** [comment]
I'm closing this issue now. Please reopen it for further problems.
