### ISSUE TITLE
Klaksyphon send blank image

### ISSUE THREAD

**Issue by caetanobr** [keijiro/KlakSyphon#4]
Hi, 
I added klak to the main camera but the syphon signal its sends its blank. Tryied on Arena and also to simpleclient from Syphon website...same results
using Unity 2018..

Any advice is much apreciatted

Thnks!

**Comment by keijiro** [comment]
KlakSyphon only supports Metal. Please check if Unity is running in Metal mode.

**Comment by caetanobr** [comment]
yep. Its seens I was running it out in light mode for iOS. Now its running smooth. Thanks for your reply. 
Awesome work by the way!

Cheers from Bahia-BR!
