### ISSUE TITLE
Unity2018.2.2f1 can't work?

### ISSUE THREAD

**Issue by ebleeye** [keijiro/KlakSyphon#5]
I'm using VDMX5 syphon output. I've tested with QC, and VDMX5 is sending successfully. 

Then I open the Test Scene (Software already set to VDMX5), do nothing, Hit play, but nothing happened. 

Do I need to do some more setup in unity? Or KlakSyphon just can't work with Unity2018.2.2f1?

**Comment by keijiro** [comment]
Please check if Unity is running in Metal mode. See the title bar of Unity Editor -- it should include `<Metal>` tag. If it only has `<OpenGL>` tag, you should check if your device supports Metal.

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen for further questions.
