### ISSUE TITLE
Can this package work in HDRP?

### ISSUE THREAD

**Issue by jieliou** [keijiro/KlakSyphon#6]
Hi, I'm new to Unity and VJ.
I use Syphon in HDRP scene but it only showed up black result. 
I'm wondering if this package have any possible work in HDRP?
Thanks a lot!

**Comment by keijiro** [comment]
It only works in the render texture mode. Create a render texture, set it as Target Texture in the main camera, then set it as Source Texture in the Syphon Server component.

**Comment by jieliou** [comment]
Thanks for quickly reply. 
But I'm sorry that I'm so new to Unity. I'm not following up the "set it as Source Texture in the Syphon Server component." part. The Syphon Server component seems only Alpha Support option. 
Thanks again for your reply. 
![image](https://user-images.githubusercontent.com/43317676/45598097-a543f880-ba08-11e8-9f3e-44b6dbd48ff2.png)

**Comment by keijiro** [comment]
Syphon Server works in camera capture mode when attached to a camera object. You have to attach the server to a non-camera object.

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen for further questions.
