### ISSUE TITLE
ParticleSystem and alpha problem

### ISSUE THREAD

**Issue by vibber** [keijiro/KlakSyphon#7]
Hi and thanks for this great package.
I encountered an issue. Steps to reproduce: Create new project, add particle system and add a cube, put syphon server on camera and enable alpha. Open Syphon Recorder (or another app that supports syphon with transparency e.g. madmapper) and there is a blank screen. Particle system does not show up but other game object displays fine.

I am on latest klaksyphon and latest unity

What can this be and is there a workaraound?

**Comment by keijiro** [comment]
The default particle shader in Unity doesn't write to alpha. You can check it in the Scene view with changing it to Alpha Channel mode (from the drop-down menu in the upper left side of the window).

How about using the Standard Particle shader? Create a new material and change its shader to "Particles/Standard Surface".

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen for further questions.
